# Generated by Django 2.2.1 on 2019-05-22 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(db_index=True, max_length=255, null=True, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('birthday', models.DateField(null=True)),
                ('email', models.CharField(db_index=True, max_length=255, null=True, unique=True)),
                ('mobile_number', models.CharField(db_index=True, max_length=255, null=True, unique=True)),
                ('gender', models.PositiveSmallIntegerField(choices=[(0, 'Prefer Not to Say'), (1, 'Male'), (2, 'Female')], default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
