# Generated by Django 2.2 on 2019-05-04 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Prefer Not to Say'), (1, 'Male'), (2, 'Female')], default=0),
        ),
    ]
