# Generated by Django 2.2.1 on 2019-05-22 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('positions', '0001_initial'),
        ('churches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_status', models.PositiveSmallIntegerField(choices=[(0, 'Created'), (1, 'Updated'), (2, 'Deleted')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='churches.Church')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='church_membership_creations', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='church_membership_deletions', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='church_members', to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='church_positions', to='positions.Position')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='church_membership_updates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
